name: Node.js CI

on:
  pull_request:
    branches: [develop]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          password: ${{ secrets.CD_PASSWORD }}
          port: 22
          script: |
            cd ~
            cd ../repos/Experiencia-Impro@dev
            git fetch origin
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git pull origin ${{ steps.extract_branch.outputs.branch }}
            rm -f .env
            touch .env
            echo 'PORT=${{ vars.PORT_DEV }}' >> .env
            echo 'PROJECT_ID=${{ secrets.PROJECT_ID }}' >> .env
            echo 'PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}' >> .env
            echo 'PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}' >> .env
            echo 'CLIENTE_EMAIL=${{ secrets.CLIENTE_EMAIL }}' >> .env
            echo 'DELIVERY_MAIL=${{ vars.DELIVERY_MAIL }}' >> .env
            echo 'DELIVERY_MAIL_PASSWORD=${{ secrets.DELIVERY_MAIL_PASSWORD }}' >> .env
            echo 'RECEIVING_MAIL=${{ vars.RECEIVING_MAIL }}' >> .env
            yarn install
            yarn build
            pm2 restart app@dev
