name: Deploy Develop

on:
  pull_request:
    branches: [develop]

jobs:
  deploy-stg:
    uses: ./.github/workflows/template-cd.yml
    with:
      ENV_SUFFIX: "@dev"
      PORT: ${{ vars.PORT_DEV }}
